# Generated by Django 6.0.3 on 2026-05-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('message_count', models.BigIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_file',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.BigIntegerField()),
                ('actual_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('KAKAO', '카카오맵'), ('TOUR_API', '관광데이터 API'), ('OSM', 'OpenStreetMap'), ('USER', '사용자 직접 입력')], default='USER', max_length=30)),
                ('source_place_id', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('FOOD', '식당'), ('LODGING', '숙소'), ('ACTIVITY', '액티비티'), ('TOUR', '관광지'), ('CAFE', '카페'), ('ETC', '기타')], default='ETC', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='AIExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('extracted_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='api.chatfile')),
            ],
            options={
                'db_table': 'ai_extraction_result',
            },
        ),
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_idx', models.BigIntegerField()),
                ('sent_time', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_travel_related', models.BooleanField(default=False)),
                ('chat_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_messages', to='api.chatfile')),
            ],
            options={
                'db_table': 'parsed_message',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.day')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.place')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='api.event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='api.event')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='RouteRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_from_route', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_recommendations', to='api.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.route')),
            ],
            options={
                'db_table': 'route_recommendation',
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='planning', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to='api.chatfile')),
            ],
            options={
                'db_table': 'trip_plan',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.tripplan'),
        ),
    ]
