# Generated by Django 6.0.3 on 2026-05-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('message_count', models.BigIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_file',
            },
        ),
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_idx', models.BigIntegerField()),
                ('sent_time', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_travel_related', models.BooleanField(default=False)),
                ('chat_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_messages', to='api.chatfile')),
            ],
            options={
                'db_table': 'parsed_message',
            },
        ),
    ]
