# Generated by Django 6.0.3 on 2026-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='entities',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_travel_span',
            field=models.BooleanField(default=False),
        ),
    ]
