# Generated by Django 6.0.3 on 2026-05-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatfile',
            name='source',
        ),
    ]
